name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1
    - name: Run make
      run: make
